### ISSUE TITLE
List of Colours and Priorities

### ISSUE THREAD

**Issue by Brousseaudan** [iho-ohi/NCWG_Baseline-Symbol#2]
Example for review
[chs_colour_rgb.txt](https://github.com/iho-ohi/NCWG_Baseline-Symbol/files/8894235/chs_colour_rgb.txt)

**Comment by Brousseaudan** [comment]
to start the conversation about colours and orders

**Comment by MikkoHovi-FI** [comment]
For comparison, Finnish colours are defined as below. Finnish name acts in our system as colour token. The English name is basically just an translation. CMYK definition is primary, RGB an alternate.

<html><body>


Name (fi) | Name (en) | RGB | CMYK | Usage examples
-- | -- | -- | -- | --
Musta | Black | 0,0,0 | C0 M0 Y0 K100 |  
Maaharmaa | Landgrey | 230,230,230 | C0 M0 Y0 K10 | Grey features that normally are on land, like builtup areas
Harmaa | Grey | 237,238,238 | C0 M0 Y0 K8 |  
Magenta | Magenta | 158,51,138 | C30 Y90 Y0 K0 |  
Korostemagenta | Highlighting magenta | 227,207,226 | C7 M23 Y0 K0 | Traffic separation zones, highlight bands for limits
Punainen | Red | 199,54,66 | C0 M90 Y65 K0 |  
Maaväri | Land tint | 250,240,203 | C0 M6 Y25 K0 |  
Keltainen | Yellow | 243,210,0 | C0 M15 Y100 K0 |  
Oranssi | Orange | 205,90,0 | C0 M75 Y100 K0 | National use. Chart boudaries on index charts only
Sininen | Blue | 229,242,252 | C15 M0 Y0 K0 | Shallow water
Vaaleansininen | Light blue | 244,249,254 | C7 M0 Y0 K0 | Medium shallow water
Tumma käyräsininen | Dark contourblue | 0,140,198 | C100 M0 Y0 K20 | 3m and 6m depth contours
Käyräsininen | Contourblue | 0,164,232 | C100 M0 Y0 K0 | Other depth contours
Valosininen | Signalblue | 0,164,232 | C100 M30 Y0 K0 | Lights
Vihreä | Green | 101,170,112 | C80 M0 Y70 K0 |  
Korostevihreä | Highlighting green | 191,212,138 | C35 M0 Y56 K0 | 


</body>
</html>

**Comment by Samlerigo** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/lerigos/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/lerigos/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/lerigos/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>


<p class=MsoNormal>UKHO Colours (values to follow)<o:p></o:p></p>



  | Colour | notes
-- | -- | --
BLK | BLACK |  
CONT | CONTOURS | Blue used for   depth contours
FLT | FLAT LAND   TINT (BUFF) | Land (we also   have a grey for Imperial charts)
GRE | GREEN | Used for   light flares/coloured light sectors on some charts
HALF | HALF TONE   BLUE | Paler blue used   in shoal water
IND |   | 30% magenta used   in busy areas to reduce clutter
ITT | INTERTIDAL   TINT | Green shade   used for intertidal areas (mix of SWB and FLT)
MAG | MAGENTA |  
PSSA | PSSA GREEN | Used along   limits
RED | RED | Used for   light flares/coloured light sectors on some charts
SEP | TSS STIPPLE | Used for TSS
SWB | SHALLOW WATER   BLUE |  
TS | TOWN STIPPLE | Used to indicate   built up areas/ large scale buildings
YEL | YELLOW | Used for   light flares/coloured light sectors on some charts



<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>

**Comment by Brousseaudan** [comment]
This is a compilation of the colours from HO's we have so far.
[NationalColourTables_2022.xlsx](https://github.com/iho-ohi/NCWG_Baseline-Symbol/files/9074475/NationalColourTables_2022.xlsx)

**Comment by ChristieEnce-NOAA** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CHRIST~1.ENC/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CHRIST~1.ENC/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>

<b><header>NOAA Custom Chart Color Palette</header></b>
</head>

<body link="#0563C1" vlink="#954F72">



Name | RGB | CMYK | Hex | Lithographic Equivalent | Usage examples
-- | -- | -- | -- | -- | --
  |   |   |   |   |  
White | 255, 255, 255 | 0, 0, 0, 0 | ffffff | NCC Only | Background, Deep Water, Maintained Depths
Black | 0, 0, 0 | 0, 0, 0, 100 | 000000 | 100% black | Chart Framework, Shoreline, Hazard Limits, Fairway Limits, Text, Symbol   Linework
  |   |   |   |   |  
Dark Gray | 114,   114, 114 | 0, 0, 0, 45 | 7b8f9c | 49% black | Depth Contours/Curves, Related Text
Medium Gray | 139,   134, 124 | 0, 4, 11, 45 | 8b867c | NCC Only | Roads, Runways, Related Text
Light Gray | 188, 188, 188 | 0, 0, 0, 26 | bcbcbc | 25% black | Exclusive Economic Zone, Maritime Boundaries, Related Text
  |   |   |   |   |  
Blue | 94,   153, 193 | 51, 21, 0, 24 | 5e99c1 | 100% blue | Civil Reservation Limits, Protected Area Limits, Related Text
Light Blue | 170,   216, 229 | 26, 6, 0, 10 | aad8e5 | 10% blue | Civil Reservation/Protected Area Limit Screen
Shallow Water Blue 1 | 175,   205, 225 | 22, 9, 0, 12 | afcde1 | NCC Only | Shallow Water (4 Depth Zones), Unsafe Water (2 Depth Zones), Area   Obstruction Fill
Shallow Water Blue 2 | 209,   221, 239 | 13, 8, 0, 6 | d1ddef | 8% blue | Unsafe Water (4 Depth Zones)
Shallow Water Blue 3 | 221,   234, 247 | 11, 5, 0, 3 | ddeaf7 | 3% blue | Safe Water (4 Depth Zones)
  |   |   |   |   |  
Gold | 151,   119, 49 | 0, 21, 68, 41 | 977731 | NCC Only | Elevation Contours, Related Text
Medium Gold | 207,   173, 93 | 0, 16, 55, 19 | cfad5d | NCC Only | Buildings (At Scale)
Urban Gold | 239, 216, 163 | 0, 10, 32, 6 | efd8a3 | 30% gold | Built-Up Areas
Land Gold | 244,   232, 193 | 0, 5, 21, 4 | f4e8c1 | 20% gold | Dry Land
  |   |   |   |   |  
Green | 84,   176, 107 | 52, 0, 39, 31 | 54b06b | 100% green | Green Lateral Aids, Swept Area Limits, Particularly Sensitive Sea Area   (PSSA) Limits, Military Anchorage Berths/Swing Circles, Related Text
Light Green | 191,   255, 191 | 25, 0, 25, 0 | bfffbf | 8% green | PSSA Limit Screen, Swept Area Fill
Intertidal Green | 214, 219, 201 | 2, 0, 8, 14 | d6dbc9 | 8% blue + 20% gold overprint | Intertidal Land, Marsh/Mangrove Areas
  |   |   |   |   |  
Magenta | 219, 73, 150 | 0, 67, 32, 14 | db4996 | 100% magenta | Regulated Area Limits, Traffic Separation Scheme Components, Red Lateral   Aids, Related Text
Light Magenta | 219,181,   242 | 10, 25, 0, 5 | dbb5f2 | 20% magenta | Regulated Area Limit Screens, Traffic Separation Zone Fill
  |   |   |   |   |  
Red | 219,   7, 7 | 0, 97, 97, 14 | db0707 | 100% red | Oil Lease Block Limits



</body>

</html>

**Comment by Samlerigo** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lerigos/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lerigos/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



  |   |   |   |  
-- | -- | -- | -- | --
UKHO Colours  |   |  
  |   |   |   |  
  | Colour | notes | RGB | CMYK
BLK | BLACK |   | 0,0,0 |  
  |   |   |   |  
TS | TOWN STIPPLE | Used to indicate built up areas/ large scale buildings | 170,170,170 |  
MAG | MAGENTA |   | 104,66,135 |  
SEP | TSS STIPPLE | Used for TSS | 220,205,217 |  
RED | RED | Used for light flares/coloured light sectors on some charts | 238,32,48 |  
  |   |   |   |  
  |   |   |   |  
YEL | YELLOW | Used for light flares/coloured light sectors on some charts | 254,188,35 |  
FLT | FLAT LAND TINT (BUFF) | Land (we also have a grey for Imperial charts) | 253,246,204 |  
ITT | INTERTIDAL TINT | Green shade used for intertidal areas (mix of SWB and FLT) | 194,225,183 |  
GRE | GREEN | Used for light flares/coloured light sectors on some charts | 0,149,95 |  
CONT | CONTOURS | Blue used for depth contours | 0,144,188 |  
SWB | SHALLOW WATER BLUE |   | 159,221,249 |  
  |   |   |   |  
HALF | HALF TONE BLUE | Paler blue used in shoal water | 220,242,253 |  
  |   |   |   |  
PSSA | PSSA GREEN | Used along limits | 190,255,150 |  
  |   |   |   |  
IND |   | 30% magenta used in busy areas to reduce clutter | 185,150,210 |  



</body>

</html>

**Comment by Brousseaudan** [comment]
[NationalColourTables_CAH_20221109 (DB).xlsx](https://github.com/iho-ohi/NCWG_Baseline-Symbol/files/9984551/NationalColourTables_CAH_20221109.DB.xlsx)
updated November 2022

**Comment by MikusRL** [comment]
@Brousseaudan When you have finished the final color table, as discussed today in the meeting, can you please add the final file here in this Issue? Then I will add the HEX colour codes and will start/finetune both colour files - svgStyle.css and colorProfile.xml.

**Comment by Brousseaudan** [comment]
For review and comments on Names and Colours.  Finalize the colour names.  To be discussed at January 11th 2023 Meeting. 
![IHO BSPT coulurs 2022-12-23 105022](https://user-images.githubusercontent.com/105673092/209363294-e343daba-fc1f-40b4-97e2-400dd148873b.jpg)
![7127IHO BSPT Colours](https://user-images.githubusercontent.com/105673092/209363305-d37637a8-00f7-452a-93fa-72ad2de6371e.jpg)

**Comment by Brousseaudan** [comment]
this was the original colour issues.  closing it at this time
