### ISSUE TITLE
CYMK to / from RGB Conversion tools

### ISSUE THREAD

**Issue by Colby-Harmon** [iho-ohi/NCWG_Baseline-Symbol#3]
The BSPT should select one color model conversion tool to use for consistency.

There are many CYMK/RGB color model conversion tools, such as [https://www.rapidtables.com/convert/color/rgb-to-cmyk.html](https://www.rapidtables.com/convert/color/rgb-to-cmyk.html).

However, since RGB values are [device dependent](https://www5.in.tum.de/lehre/vorlesungen/graphik/info/csc/COL_6.htm), there can be no universal, exact conversion from CYMK.

Further complicating matters, RGB is an additive color model (intended for light emitting, digital displays), while CYMK is a subtractive color model (intended for printed media, where colored inks are used).

I think the BSPT has at least preliminarily decided that the CYMK model will be used to define the colors used in the baseline symbology "specification," but RGBs are also very useful for quickly comparing colors in various computer applications, such as PowerPoint, Word, Excel and many graphic applications.

For the sake of consistency, the BSPT should choose one color model conversion tool for the work of the project team.

The example tool referenced above was just the first result of a Google search. Is there another that might be preferred? I used this tool to convert the New Zealand CYMKs to RGBs, but I know Finland used a different method, because I tried converting a few Finnish CYMKs and got different results than the values provided by Finland.

**Comment by Brousseaudan** [comment]
Closing this issue as we have move on past this task.
