### ISSUE TITLE
INT1 A1-A2, Chart Number 

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/NCWG_Baseline-Symbol#5]
UKHO INT1
![image](https://user-images.githubusercontent.com/72803214/202106181-37c63f9d-e409-45ff-b49a-9625858445cc.png)
![image](https://user-images.githubusercontent.com/72803214/202105407-7a5f476f-2a42-49b4-a55f-762e47315f18.png)
![image](https://user-images.githubusercontent.com/72803214/202105526-18503981-5017-4c22-8e29-647fcf5cb4de.png)

U.S. Chart No. 1
![image](https://user-images.githubusercontent.com/72803214/202105707-5c08b6ac-ce32-42a3-bcd4-d2ee9c457ee9.png)
![image](https://user-images.githubusercontent.com/72803214/202105902-89d64614-5440-4ff9-8009-d00244e78d87.png)
![image](https://user-images.githubusercontent.com/72803214/202105957-5abe1aa4-b9b7-4ca9-a2c0-0181b701f2be.png)

**Comment by ChristieEnce-NOAA** [comment]
Not encoded in s-101 and no recommendation to add to the s-101 specification.
