### ISSUE TITLE
INT1 C8, Sandhills, Dunes

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/NCWG_Baseline-Symbol#51]
UKHO INT1
![image](https://user-images.githubusercontent.com/72803214/214586577-adcf22cf-b4d4-493e-b81e-5e9475200ece.png)

U.S. Chart No. 1
![image](https://user-images.githubusercontent.com/72803214/214586610-9e9c7b66-d49c-4f6e-8e67-d22a62480e77.png)

**Comment by ChristieEnce-NOAA** [comment]
- Keep symbol? 
- Geometry
- Color(s)
- Lineweight (thin, bold)
- Line Pattern
- Symbol Instructions/Engineering Drawings
- S-57/S-101 Encoding 
- DCG Encoding
- National Symbol?
- Label Specfications
- Drawing Priority
